name: Checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    
    name: Test Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup uv
      uses: astral-sh/setup-uv@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --group dev --all-extras

    - name: Run ruff checks
      run: make checks-ruff

    - name: Run pyright checks
      run: make checks-pyright

    - name: Run tests
      run: make tests